#!/usr/bin/env bash
set -euo pipefail

# Deploy a built plugin release to the official WordPress.org SVN repository.
#
# This template is generated by the build-wordpress-plugin skill. It is
# slug-agnostic: configure it through environment variables (typically set in
# PLUGIN_SRC/.env) rather than editing the script.
#
# Required configuration:
#   PLUGIN_SLUG      Plugin slug — also the main plugin file name (e.g. my-plugin)
#   SVN_REPO_PATH    Local checkout of the WordPress.org SVN repo. Create it once with:
#                       svn co "https://plugins.svn.wordpress.org/${PLUGIN_SLUG}" "$SVN_REPO_PATH"
#
# Optional configuration (with defaults):
#   PLUGIN_SRC       Path to the built plugin source dir (default: current directory)
#   ASSETS_SRC       Path to the assets dir (banner/icon/screenshots) (default: PLUGIN_SRC/../assets)
#
# Usage:
#   ./deploy-to-svn.sh            # version read from readme.txt "Stable tag"
#   ./deploy-to-svn.sh 1.2.3      # explicit version argument

# --- Load configuration -------------------------------------------------------
PLUGIN_SLUG="${PLUGIN_SLUG:-}"
PLUGIN_SRC="${PLUGIN_SRC:-$(pwd)}"
ENV_FILE="${PLUGIN_SRC}/.env"

if [ ! -f "${ENV_FILE}" ] && [ -f "${PLUGIN_SRC}/.env.example" ]; then
    ENV_FILE="${PLUGIN_SRC}/.env.example"
fi

if [ -f "${ENV_FILE}" ]; then
    set -a
    source "${ENV_FILE}"
    set +a
fi

if [ -z "${PLUGIN_SLUG:-}" ]; then
    echo "Error: PLUGIN_SLUG is not set."
    echo "Set it in ${PLUGIN_SRC}/.env or export it before running this script."
    exit 1
fi

SVN_REPO="${SVN_REPO_PATH:-}"
SVN_TRUNK="${SVN_REPO}/trunk"
SVN_TAGS="${SVN_REPO}/tags"
SVN_ASSETS="${SVN_REPO}/assets"

if [ -z "${SVN_REPO}" ]; then
    echo "Error: SVN_REPO_PATH is not set."
    echo "Set it in ${ENV_FILE} or export it before running this script."
    echo "Create the checkout once with:"
    echo "  svn co \"https://plugins.svn.wordpress.org/${PLUGIN_SLUG}\" \"\$SVN_REPO_PATH\""
    exit 1
fi

# --- Detect version -----------------------------------------------------------
VERSION="${1:-}"
if [ -z "${VERSION}" ]; then
    VERSION=$(grep -i "^Stable tag:" "${PLUGIN_SRC}/readme.txt" | awk '{print $NF}')
fi

if [ -z "${VERSION}" ]; then
    echo "Error: Could not detect version. Pass it as an argument or set Stable Tag in readme.txt."
    exit 1
fi

echo "Using version: ${VERSION}"

# --- Copy plugin files to trunk, respecting .distignore -----------------------
echo "Cleaning ${SVN_TRUNK}..."
rm -rf "${SVN_TRUNK:?}"/*
mkdir -p "${SVN_TRUNK}"

echo "Copying plugin files to trunk..."
DISTIGNORE="${PLUGIN_SRC}/.distignore"
EXCLUDE_PATTERNS=()

if [ -f "${DISTIGNORE}" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
        # Skip empty lines and comments
        [[ -z "$line" ]] && continue
        [[ "$line" =~ ^# ]] && continue
        EXCLUDE_PATTERNS+=("$line")
    done < "${DISTIGNORE}"
fi

cd "${PLUGIN_SRC}"

rsync -av --delete \
    $(printf -- '--exclude=%s ' "${EXCLUDE_PATTERNS[@]}") \
    "${PLUGIN_SRC}/" "${SVN_TRUNK}/"

# Ensure excluded patterns are not present in trunk (rsync --delete may not
# remove excluded files that were previously tracked).
cd "${SVN_TRUNK}"
for pattern in "${EXCLUDE_PATTERNS[@]}"; do
    [[ -z "$pattern" ]] && continue
    [[ "$pattern" =~ ^# ]] && continue
    for f in ${pattern}; do
        if [ -e "${SVN_TRUNK}/${f}" ]; then
            rm -rf "${SVN_TRUNK}/${f}"
        fi
    done
done

# Mark files added/removed in SVN so status is clean.
if command -v svn &>/dev/null && [ -d "${SVN_REPO}/.svn" ]; then
    cd "${SVN_REPO}"
    svn add trunk/ --force 2>/dev/null || true
    # Remove any tracked files that no longer exist
    MISSING=$(svn status trunk/ | grep '^!' || true | awk '{print $2}')
    [ -n "${MISSING}" ] && xargs -r svn rm <<< "${MISSING}" || true
fi

echo "Plugin files copied to trunk."

# --- Copy assets --------------------------------------------------------------
echo "Copying assets..."
ASSETS_SRC="${ASSETS_SRC:-${PLUGIN_SRC}/../assets}"
if [ -d "${ASSETS_SRC}" ] && [ "$(ls -A "${ASSETS_SRC}")" ]; then
    rm -rf "${SVN_ASSETS:?}"/*
    rsync -av "${ASSETS_SRC}/" "${SVN_ASSETS}/"
    if command -v svn &>/dev/null && [ -d "${SVN_REPO}/.svn" ]; then
        cd "${SVN_REPO}"
        svn add assets/ --force 2>/dev/null || true
        MISSING=$(svn status assets/ | grep '^!' || true | awk '{print $2}')
        [ -n "${MISSING}" ] && xargs -r svn rm <<< "${MISSING}" || true
    fi
    echo "Assets copied."
else
    echo "No assets to copy."
fi

# --- Optionally create a tag --------------------------------------------------
if [ -n "${VERSION}" ]; then
    TAG_DIR="${SVN_TAGS}/${VERSION}"
    if [ -d "${TAG_DIR}" ]; then
        echo "Tag ${VERSION} already exists. Skipping tag creation."
    else
        echo "Creating tag ${VERSION}..."
        svn copy "${SVN_TRUNK}" "${TAG_DIR}"
        echo "Tag created. Remember to svn commit if you haven't already."
    fi
fi

echo "Done. Remember to 'svn commit' if you haven't already."
